### ISSUE TITLE
User Story #28/#30: Retrieve Matches  

### ISSUE THREAD

**Issue by pqalzm6** [leejr0/cs414-f19-001-Spaghetti-Coders#54]
As a front-end developer, I need to retrieve match information from the back-end's database.

Acceptance Criteria:
Test that a game's state can be saved to the database.
Test that a game's state can be retrieved from the database.
Test successful front-end and back-end communication.
Test retrieving information from a game that doesn't exist.

**Comment by leejr0** [comment]
side note: Create a back-end class to retrieve information from the database about past and current games and send it to front-end class "Homepage"
